// academyData.js
LawAIApp.AcademyData = {
  // 原始数据（符合 Phase 6 规范 + 向后兼容别名）
  academies: [
    {
      id: 'academy_ai',
      name: 'AI Academy',
      shortName: 'AI',
      description: 'Master Artificial Intelligence from fundamentals to advanced.',
      icon: '🤖',
      coverImage: '',
      themeColor: '#3b82f6',
      difficulty: 'Beginner',
      category: 'Technology',
      status: 'active',
      enabled: true,
      order: 1,
      estimatedHours: 48,
      estimatedLessons: 365,
      progress: 0,
      completedLessons: 0,
      favorite: false,
      bookmark: false,
      lastOpened: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      // 兼容别名 (UI 使用)
      title: 'AI Academy',          // 等于 name
      totalLessons: 365             // 等于 estimatedLessons
    },
    {
      id: 'academy_programming',
      name: 'Programming Academy',
      shortName: 'Programming',
      description: 'Learn coding from scratch with modern languages.',
      icon: '💻',
      coverImage: '',
      themeColor: '#22c55e',
      difficulty: 'Beginner',
      category: 'Programming',
      status: 'coming_soon',
      enabled: false,
      order: 2,
      estimatedHours: 0,
      estimatedLessons: 0,
      progress: 0,
      completedLessons: 0,
      favorite: false,
      bookmark: false,
      lastOpened: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      title: 'Programming Academy',
      totalLessons: 0
    },
    {
      id: 'academy_hardware',
      name: 'Computer Hardware Academy',
      shortName: 'Hardware',
      description: 'Understand how computers work inside out.',
      icon: '🖥️',
      coverImage: '',
      themeColor: '#8b5cf6',
      difficulty: 'Intermediate',
      category: 'Technology',
      status: 'coming_soon',
      enabled: false,
      order: 3,
      estimatedHours: 0,
      estimatedLessons: 0,
      progress: 0,
      completedLessons: 0,
      favorite: false,
      bookmark: false,
      lastOpened: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      title: 'Computer Hardware Academy',
      totalLessons: 0
    },
    {
      id: 'academy_automotive',
      name: 'Automotive Academy',
      shortName: 'Automotive',
      description: 'Dive into car mechanics and modern automotive tech.',
      icon: '🚗',
      coverImage: '',
      themeColor: '#f59e0b',
      difficulty: 'Beginner',
      category: 'Automotive',
      status: 'coming_soon',
      enabled: false,
      order: 4,
      estimatedHours: 0,
      estimatedLessons: 0,
      progress: 0,
      completedLessons: 0,
      favorite: false,
      bookmark: false,
      lastOpened: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      title: 'Automotive Academy',
      totalLessons: 0
    },
    {
      id: 'academy_finance',
      name: 'Finance & Economics Academy',
      shortName: 'Finance',
      description: 'Build financial literacy and economic thinking.',
      icon: '💰',
      coverImage: '',
      themeColor: '#ef4444',
      difficulty: 'Intermediate',
      category: 'Finance',
      status: 'coming_soon',
      enabled: false,
      order: 5,
      estimatedHours: 0,
      estimatedLessons: 0,
      progress: 0,
      completedLessons: 0,
      favorite: false,
      bookmark: false,
      lastOpened: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      title: 'Finance & Economics Academy',
      totalLessons: 0
    },
    {
      id: 'academy_health',
      name: 'Health Academy',
      shortName: 'Health',
      description: 'Learn about physical and mental well‑being.',
      icon: '❤️',
      coverImage: '',
      themeColor: '#ec4899',
      difficulty: 'Beginner',
      category: 'Health',
      status: 'coming_soon',
      enabled: false,
      order: 6,
      estimatedHours: 0,
      estimatedLessons: 0,
      progress: 0,
      completedLessons: 0,
      favorite: false,
      bookmark: false,
      lastOpened: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      title: 'Health Academy',
      totalLessons: 0
    },
    {
      id: 'academy_nutrition',
      name: 'Nutrition Academy',
      shortName: 'Nutrition',
      description: 'Master the science of food and diet.',
      icon: '🥗',
      coverImage: '',
      themeColor: '#10b981',
      difficulty: 'Beginner',
      category: 'Health',
      status: 'coming_soon',
      enabled: false,
      order: 7,
      estimatedHours: 0,
      estimatedLessons: 0,
      progress: 0,
      completedLessons: 0,
      favorite: false,
      bookmark: false,
      lastOpened: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      title: 'Nutrition Academy',
      totalLessons: 0
    },
    {
      id: 'academy_english',
      name: 'English Academy',
      shortName: 'English',
      description: 'Improve your English language skills.',
      icon: '🇬🇧',
      coverImage: '',
      themeColor: '#6366f1',
      difficulty: 'Beginner',
      category: 'Education',
      status: 'coming_soon',
      enabled: false,
      order: 8,
      estimatedHours: 0,
      estimatedLessons: 0,
      progress: 0,
      completedLessons: 0,
      favorite: false,
      bookmark: false,
      lastOpened: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      title: 'English Academy',
      totalLessons: 0
    }
  ],

  getAcademyById(id) {
    return this.academies.find(a => a.id === id) || null;
  }
};
