// ===========================================
// curriculumContentSeeder.js
// 课程内容播种器：为已生成的课程填充示例教学文本
// ===========================================
LawAIApp.CurriculumContentSeeder = {
  seedLessonContent(lessonId) {
    const node = LawAIApp.GraphNodeManager.getNode(lessonId);
    if (!node) return;
    // 模拟 AI 生成的内容（未来可由真实 API 填充）
    const content = `### ${node.title}\n\n` +
                    `Welcome to this lesson on **${node.category || 'this topic'}**. ` +
                    `Here you will learn the key concepts and practice applying them.\n\n` +
                    `**Key Points:**\n- Understand the definition\n- Explore real-world examples\n- Complete the practice task below\n\n` +
                    `_Generated by CivOS Content Factory._`;
    // 将内容存储到 LessonEngine 或自定义存储中
    if (LawAIApp.LessonEngine?.updateLesson) {
      LawAIApp.LessonEngine.updateLesson(lessonId, { content });
    } else {
      // 备用：直接存 Storage
      const lessonsContent = LawAIApp.StorageEngine.get('seeded_lessons_content', {});
      lessonsContent[lessonId] = content;
      LawAIApp.StorageEngine.set('seeded_lessons_content', lessonsContent);
    }
  },

  // 对当前所有自动生成的课程播种
  seedAllGeneratedLessons() {
    const nodes = LawAIApp.GraphNodeManager.getAllNodes();
    nodes.forEach(n => {
      if (n.type === 'lesson' && n.id.startsWith('gen_')) {
        this.seedLessonContent(n.id);
      }
    });
    console.log('Content seeding completed.');
  }
};
