// moduleData.js
LawAIApp.ModuleData = {
  modules: [
    // AI Foundation modules
    {
      id: 'module_ai_basics',
      courseId: 'course_ai_foundation',
      academyId: 'academy_ai',
      categoryId: 'cat_ai',
      name: 'AI Basics',
      shortName: 'AI Basics',
      description: 'Introduction to artificial intelligence concepts.',
      icon: '🧠',
      themeColor: '#3b82f6',
      difficulty: 'Beginner',
      difficultyScore: 10,
      status: 'published',
      enabled: true,
      order: 1,
      estimatedMinutes: 40,
      estimatedLessons: 2,
      estimatedXP: 100,
      learningObjectives: ['Define AI', 'List AI applications', 'Understand AI vs ML'],
      skillsEarned: ['AI Literacy'],
      prerequisites: [],
      recommendedNext: ['module_ml_intro'],
      tags: ['AI', 'Basics'],
      progress: 0,
      completedLessons: 0,
      completionRule: 'complete_all_lessons',
      favorite: false,
      bookmark: false,
      lastOpened: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      version: '1.0'
    },
    {
      id: 'module_ml_intro',
      courseId: 'course_ai_foundation',
      academyId: 'academy_ai',
      categoryId: 'cat_ai',
      name: 'Introduction to Machine Learning',
      shortName: 'ML Intro',
      description: 'Learn the basics of machine learning.',
      icon: '📊',
      themeColor: '#3b82f6',
      difficulty: 'Beginner',
      difficultyScore: 20,
      status: 'published',
      enabled: true,
      order: 2,
      estimatedMinutes: 50,
      estimatedLessons: 2,
      estimatedXP: 120,
      learningObjectives: ['Understand supervised vs unsupervised learning', 'Build a simple model'],
      skillsEarned: ['ML Fundamentals'],
      prerequisites: ['module_ai_basics'],
      recommendedNext: [],
      tags: ['Machine Learning', 'Basics'],
      progress: 0,
      completedLessons: 0,
      completionRule: 'complete_all_lessons',
      favorite: false,
      bookmark: false,
      lastOpened: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      version: '1.0'
    },
    // Prompt Engineering modules
    {
      id: 'module_prompt_basics',
      courseId: 'course_prompt_engineering',
      academyId: 'academy_ai',
      categoryId: 'cat_ai',
      name: 'Prompt Basics',
      shortName: 'Prompt Basics',
      description: 'Fundamentals of crafting prompts.',
      icon: '✍️',
      themeColor: '#8b5cf6',
      difficulty: 'Intermediate',
      difficultyScore: 40,
      status: 'published',
      enabled: true,
      order: 1,
      estimatedMinutes: 35,
      estimatedLessons: 2,
      estimatedXP: 90,
      learningObjectives: ['Write clear prompts', 'Understand prompt structure'],
      skillsEarned: ['Prompt Writing'],
      prerequisites: ['module_ai_basics'],
      recommendedNext: ['module_advanced_prompt'],
      tags: ['Prompt', 'ChatGPT'],
      progress: 0,
      completedLessons: 0,
      completionRule: 'complete_all_lessons',
      favorite: false,
      bookmark: false,
      lastOpened: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      version: '1.0'
    },
    {
      id: 'module_advanced_prompt',
      courseId: 'course_prompt_engineering',
      academyId: 'academy_ai',
      categoryId: 'cat_ai',
      name: 'Advanced Prompt Engineering',
      shortName: 'Adv. Prompt',
      description: 'Master advanced techniques.',
      icon: '✨',
      themeColor: '#8b5cf6',
      difficulty: 'Advanced',
      difficultyScore: 60,
      status: 'published',
      enabled: true,
      order: 2,
      estimatedMinutes: 45,
      estimatedLessons: 2,
      estimatedXP: 110,
      learningObjectives: ['Chain-of-thought', 'Multi-step prompts', 'Optimize for different models'],
      skillsEarned: ['Prompt Optimization'],
      prerequisites: ['module_prompt_basics'],
      recommendedNext: [],
      tags: ['Prompt', 'Advanced'],
      progress: 0,
      completedLessons: 0,
      completionRule: 'complete_all_lessons',
      favorite: false,
      bookmark: false,
      lastOpened: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      version: '1.0'
    }
  ],

  getById(id) {
    return this.modules.find(m => m.id === id) || null;
  },

  getByCourseId(courseId) {
    return this.modules.filter(m => m.courseId === courseId);
  },

  getByAcademyId(academyId) {
    return this.modules.filter(m => m.academyId === academyId);
  }
};
